site_name: docutil
site_description: Enterprise Document Utility Toolkit
site_author: Richie Garafola
repo_url: https://github.com/RichieGarafola/docutil
repo_name: RichieGarafola/docutil

docs_dir: docs
strict: true

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: blue
      accent: deep orange
  features:
    - navigation.sections
    - navigation.instant
    - navigation.top
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - search.suggest
    - search.highlight


nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - CLI Reference: cli-reference.md
  - Versioning System: versioning.md
  - Architecture: architecture.md
  - Contributing: contributing.md
  - Change Log: CHANGELOG.md

  - Architecture (Technical):
      - Technical Design: architecture/technical-design.md

  - Planning:
      - Project Charter: planning/project-charter.md
      - Requirements: planning/requirements.md
      - Timeline: planning/timeline.md
      - Risk Register: planning/risk-register.md
      - Deployment Plan: planning/deployment-plan.md
      - Post Implementation Review: planning/post-implementation-review.md

  - QA:
      - Test Plan: qa/test-plan.md
      - CLI Functional Guide: qa/cli-functional-test-guide.md
      - QA Signoff: qa/qa-signoff.md

  - Training:
      - Training Plan: training/training-plan.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RichieGarafola/docutil

copyright: Copyright Â© 2026 Richie Garafola
